services:
  # Cấu hình Database PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: smart_home_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Cấu hình Java Backend
  api:
    build: .
    container_name: java_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/smart_home_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
      DB_HOST: db
      DB_PORT: 5432

  # Cấu hình MQTT Broker (Mosquitto)
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ../mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ../mosquitto/data:/mosquitto/data
      - ../mosquitto/log:/mosquitto/log

volumes:
  postgres_data:
